### PR TITLE
Ability to maintain aspect ratio for fromDataURL

### PR DESCRIPTION
**Pull request by garhbod**
Haven't tested but was extracted from my working javascript

### CODE REVIEW

**Comment by Zigonja** [comment]
Will this ever be implemented?

**Comment by UziTech** [comment]
closing as stale

**Comment by garhbod** [comment]
Shame this wasn't ever considered. Or is there another implementation of this?

**Comment by UziTech** [comment]
This seems like something that could be handled outside of this library. They can calculate the ratio and pass that in. We want to keep this library small and not add too many more options.

**Pull request closed without merging**
