### PR TITLE
added support for PointerEvents

### PR DESCRIPTION
**Pull request by onigunn**
In order to capture events from input devices like a microsoft stylus,
we have to handle pointer events too.

Fixes issue #245

### CODE REVIEW

**Comment by szimek** [comment]
@onigunn Thanks! I'll most likely release some other stuff first and then will release a version with your PR as a beta release. 

One question though: Chrome on desktop supports pointer events as well, won't it trigger event handlers twice - once via mouse events and once via pointer events?

**Comment by onigunn** [comment]
@szimek I first thought so but Firefox behaves strange on PointerEvent detection. Mouse events stopped working. So I left the condition out. After some digging around it seems that pointer events must call `event.preventDefault()` to keep mouse events going. See: [MDN PointerEvent Reference](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent)

I changed that but currently have to wait for the surface and stylus to check if everything working as expected there too. I'll keep you updated and will update my PR next week.

**Comment by szimek** [comment]
@onigunn Thanks! Unfortunately I don't have access to a tablet with stylus, so I'm not sure if there's any way for me to actually test it. I'll wait for your update then ;)

**Comment by onigunn** [comment]
@szimek Sorry for the delay. Test device was missing :) 

Seems to work. Tested on Edge and Chrome on given Surface Pro 5 (or 4 - thb I don't exactly know which version) with Stylus. Updated my PR.

**Comment by szimek** [comment]
@onigunn Thanks! I'll release a beta version of 2.4.0 with this PR in the next few days and see if it causes any new issues. If it doesn't, I'll release it as stable.

**Comment by szimek** [comment]
Hey, I finally had some time to look into it and, unfortunately, I'm not really confident about merging it without testing it first. I'll try to finally find some device with a stylus ;)

You wrote:
> I first thought so but Firefox behaves strange on PointerEvent detection.

Most likely it is caused by broken detection code:
```js
window.PointerEvent !== 'undefined'
``` 
should either be 
```js
window.PointerEvent !== undefined
``` 
or 
```js
typeof window.PointerEvent !== 'undefined'
```

**Comment by onigunn** [comment]
@szimek 
Yeah, totally right. Detection is broken here. Sadly I cannot provide you anymore changes because I don't have test device anymore :)

If you like you can close this PR. Or maybe a test device will show up and it will be merged.

**Comment by szimek** [comment]
@onigunn Thank you again for your PR! I've just added an initial support for pointer events in the latest beta version (3.0.0-beta.3).

**Pull request closed without merging**
