### PR TITLE
Adding `import`

### PR DESCRIPTION
**Pull request by ThomasLandauer**

### CODE REVIEW

**Comment by UziTech** [comment]
How it is imported will depend on how it is loaded so this won't be valid for everyone.

**Comment by ThomasLandauer** [comment]
I had trouble yesterday figuring this out, so I thought I'd share it.
Which other ways do exist? Maybe you could show them *all*, like in the "Installation" section where you're showing *multiple* ways.

**Comment by UziTech** [comment]
If you add the script tag to the page than it is added as a global so there is no need to import.

**Comment by ThomasLandauer** [comment]
So what about something like this?:
```javascript
// If you don't add it via `<script>`:
import SignaturePad from "signature_pad";
```

**Comment by UziTech** [comment]
Where it says
> This library is provided as UMD (Universal Module Definition) and ES6 module.

We could change it to:
> This library is provided as UMD (Universal Module Definition) and ES6 module with a default export.

**Comment by ThomasLandauer** [comment]
I didn't know the `signature_pad` part of this line - so I had to guess it:

> import SignaturePad from "signature_pad";

This info is what I'm trying to get into README ;-)
Or is this *always* the same as in `yarn add signature_pad` - so that everybody knows it anyway?

**Comment by UziTech** [comment]
Ya that is just the package name. It is always the same to install and import.

**Comment by ThomasLandauer** [comment]
OK, thanks, then let's leave it as it is ;-)

**Pull request closed without merging**
