### PR TITLE
Undo functionality, cropped option

### PR DESCRIPTION
**Pull request by mymattcarroll**
### Unreleased
* Added callback to `fromDataURL()` function to allow user to know when canvas has been updated. [mymattcarroll](https://github.com/mymattcarroll)
* Added `undo()` function to revert the last stroke. [mymattcarroll](https://github.com/mymattcarroll)
* Added `toDataURLCropped()` function to get the data url of the `SignaturePad` with whitespace cropped (_does not modify the `SignaturePad`_). [mymattcarroll](https://github.com/mymattcarroll)
* Fixed resizing image issues. [mymattcarroll](https://github.com/mymattcarroll)

### CODE REVIEW

**Comment by mymattcarroll** [comment]
@szimek, I would really like these changes merged upstream, however, I have noticed that you have made significant changes in this commit: [ES6! Babel! ESLint! UMD!](https://github.com/szimek/signature_pad/commit/01594d67d669abd4e9e3a99215530ebfb8a85694).

If you plan on merging these changes in soon, I would be happy to rebase/redo my changes. If you approve of the changes that I have made, please let me know what you would prefer.

**Comment by szimek** [comment]
Hey, thanks for your PR! I really don't have any free time right now and will take a look at all issues/PRs at the end of year. 

I really want to merge the `draw-signature-from-point-data` branch first, because collecting all points will allow me to finally add a few things I wanted to add for a long time (export to SVG, tests, profile and optimize the library etc.)

**Comment by mymattcarroll** [comment]
Thanks for the quick reply @szimek.

Would you recommend rebasing on `draw-signature-from-point-data` now in preparation for it to be merged or are there still changes to be made to the branch?

What I meant by _does not modify the `SignaturePad`_ was it does not modify the existing canvas that was used to create the `SignaturePad`. It only reads the image from it and creates a new `Canvas` before returning the `dataURL`

**Comment by mymattcarroll** [comment]
Closed so that `draw-signature-from-point-data` can be merged first, will open another PR once it has been merged.

**Comment by szimek** [comment]
@mymattcarroll I need to figure out why the generated SVG is not visible in a browser, if it should be base64 encoded like pngs and jpegs or not and once it's done, I'll merge it and release it as a beta version, so that everyone can see if no bugs were introduced.

**Comment by mymattcarroll** [comment]
Thanks for the update @szimek :)

**Pull request closed without merging**
